const PROCESSOR_EXPRESSION_PREFIX = 'n-',
	TEMPLATE_TAG = 'nt',
	PROCESSOR_EXPRESSION_SEPARATOR = '-',
	PROCESSOR_EXPRESSION_CONDITION_POSTFIX = 'if',
	COMPONENT_ID_PREFIX = 'not_component_',
	PART_ID_PREFIX = 'not_part_',
	DEFAULT_PLACER = 'place',
	DEFAULT_PLACER_LOOP = 'placeAfter';

const OPTS = {
	PROCESSOR_EXPRESSION_PREFIX,
	TEMPLATE_TAG,
	PROCESSOR_EXPRESSION_SEPARATOR,
	PROCESSOR_EXPRESSION_CONDITION_POSTFIX,
	DEFAULT_PLACER,
	COMPONENT_ID_PREFIX,
	PART_ID_PREFIX,
	DEFAULT_PLACER_LOOP
};

export default OPTS;
